version: '3.3'

services:
    app:
        build: ./
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - '/app/node_modules'

        expose:
           - '8080'
    database:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=Suranjith
            - MYSQL_ROOT_HOST=%
        ports:
            - '3366:3306'
        expose:
            - '3306'

        volumes:         
            - /:/var/lib/mysql
